name: first workflow 

on: 
  push:
    branches:
      - main
jobs:
  examble-job:
    runs-on: ubuntu-latest
    steps:
    - name: print workflow message 
      run: echo "welcome to our github actions workflow "
    - name: checkout repo
      uses: actions/checkout@v5.0.0
    - name: list repo files 
      run: ls -la
